# Generated by Django 5.1 on 2024-09-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_catogorias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogorias',
            new_name='Categoria',
        ),
    ]
