# Generated by Django 5.1.1 on 2024-09-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='documento_contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos'),
        ),
    ]
