# Generated by Django 5.1 on 2024-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_foto_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='category',
            field=models.CharField(choices=[('ELEC', 'Electronics'), ('FASH', 'Fashion'), ('FOOD', 'Food'), ('BOOK', 'Books')], default='ELEC', max_length=10),
        ),
    ]
